// <auto-generated />
using System;
using MarketAnalysisWebApi.DbEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketAnalysisWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbBusinessOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<double>("CurrentPriceNDS")
                        .HasColumnType("double precision");

                    b.Property<string>("NameByProject")
                        .HasColumnType("text");

                    b.Property<string>("NameBySupplier")
                        .HasColumnType("text");

                    b.Property<string>("SupplierSiteURL")
                        .HasColumnType("text");

                    b.Property<string>("WarehouseLocation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("OffersTable");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullCompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("INN")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("JurAdress")
                        .HasColumnType("text");

                    b.Property<string>("KPP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("LogoFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortCompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyTypeId");

                    b.HasIndex("LogoFileId");

                    b.ToTable("CompaniesTable");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompanyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TypeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CompanyTypesTable");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbEquipRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("RequestId");

                    b.ToTable("EquipRequestTable");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfigTypeId");

                    b.ToTable("EquipmentTable");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbFavoriteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoritesTable");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationRegion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameByProjectDocs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfigTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectRequestsTable");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbRequestConfigType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigTypeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationTypesTable");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbSupplierUserCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplierUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SupplierUserId");

                    b.ToTable("SupplierUsersCompaniesTable");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("UsersTable");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UsersRolesTable");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.DbKnsConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivePumpsCount")
                        .HasColumnType("integer");

                    b.Property<int>("EnvironmentTemperature")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedDiameterOfPumpStation")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedHeightOfPumpStation")
                        .HasColumnType("integer");

                    b.Property<bool>("ExplosionProtection")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasManyExitPressurePipelines")
                        .HasColumnType("boolean");

                    b.Property<int>("InsulatedHousingDepth")
                        .HasColumnType("integer");

                    b.Property<int>("PType")
                        .HasColumnType("integer");

                    b.Property<double>("Perfomance")
                        .HasColumnType("double precision");

                    b.Property<int>("Place")
                        .HasColumnType("integer");

                    b.Property<int>("PowerContactsToController")
                        .HasColumnType("integer");

                    b.Property<int>("PressurePipelineDepth")
                        .HasColumnType("integer");

                    b.Property<int>("PressurePipelineDiameter")
                        .HasColumnType("integer");

                    b.Property<int>("PressurePipelineDirectionInHours")
                        .HasColumnType("integer");

                    b.Property<int>("PressurePipelineMaterial")
                        .HasColumnType("integer");

                    b.Property<int>("PumpsToWarehouseCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<double>("RequiredPumpPressure")
                        .HasColumnType("double precision");

                    b.Property<int>("ReservePumpsCount")
                        .HasColumnType("integer");

                    b.Property<int>("SupplyPipelineDepth")
                        .HasColumnType("integer");

                    b.Property<int>("SupplyPipelineDiameter")
                        .HasColumnType("integer");

                    b.Property<int>("SupplyPipelineDirectionInHours")
                        .HasColumnType("integer");

                    b.Property<int>("SupplyPipelineMaterial")
                        .HasColumnType("integer");

                    b.Property<int>("Units")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("DbKnsConfig");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbImageFileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DbImageFileModel");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbBusinessOffer", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompany", "Company")
                        .WithMany("CompanyOffers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompany", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompanyType", "CompanyType")
                        .WithMany("Companies")
                        .HasForeignKey("CompanyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.FileStorages.DbImageFileModel", "LogoImage")
                        .WithMany("Companies")
                        .HasForeignKey("LogoFileId");

                    b.Navigation("CompanyType");

                    b.Navigation("LogoImage");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbEquipRequest", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbEquipment", "Equipment")
                        .WithMany("EquipRequests")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", "ProjectRequest")
                        .WithMany("EquipRequest")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("ProjectRequest");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbEquipment", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbRequestConfigType", "Type")
                        .WithMany("Equipments")
                        .HasForeignKey("ConfigTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbFavoriteRequest", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", "request")
                        .WithMany("FavoriteRequests")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", "User")
                        .WithMany("FavoriteRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("request");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbRequestConfigType", "RequestConfigType")
                        .WithMany("ProjectRequests")
                        .HasForeignKey("ConfigTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", "User")
                        .WithMany("UsersRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestConfigType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbSupplierUserCompany", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompany", "SupplierCompany")
                        .WithMany("CompanyUsersLinks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", "SupplierUser")
                        .WithMany("CompanyUsersLinks")
                        .HasForeignKey("SupplierUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplierCompany");

                    b.Navigation("SupplierUser");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbUserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.DbKnsConfig", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", "Request")
                        .WithMany("KnsConfigs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompany", b =>
                {
                    b.Navigation("CompanyOffers");

                    b.Navigation("CompanyUsersLinks");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompanyType", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbEquipment", b =>
                {
                    b.Navigation("EquipRequests");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", b =>
                {
                    b.Navigation("EquipRequest");

                    b.Navigation("FavoriteRequests");

                    b.Navigation("KnsConfigs");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbRequestConfigType", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("ProjectRequests");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", b =>
                {
                    b.Navigation("CompanyUsersLinks");

                    b.Navigation("FavoriteRequests");

                    b.Navigation("UsersRequests");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbUserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbImageFileModel", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
