// <auto-generated />
using System;
using MarketAnalysisWebApi.DbEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketAnalysisWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbAccountRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RequestId");

                    b.ToTable("AccountRequests", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbBusinessAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Coins")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BusinessAccounts", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbBusinessOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BussinessAccId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CertificateFileId")
                        .HasColumnType("uuid");

                    b.Property<double>("CurrentPriceNDS")
                        .HasColumnType("double precision");

                    b.Property<double>("CurrentPriceNoNDS")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("DbCompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryTerms")
                        .HasColumnType("text");

                    b.Property<string>("GarantyPeriod")
                        .HasColumnType("text");

                    b.Property<string>("ManufacturerCountry")
                        .HasColumnType("text");

                    b.Property<string>("NameByProject")
                        .HasColumnType("text");

                    b.Property<string>("NameBySupplier")
                        .HasColumnType("text");

                    b.Property<Guid?>("OfferFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("OffersNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("PassportFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("text");

                    b.Property<Guid?>("PlanFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierSiteURL")
                        .HasColumnType("text");

                    b.Property<DateTime>("SupportingDocumentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WarehouseLocation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BussinessAccId");

                    b.HasIndex("CertificateFileId");

                    b.HasIndex("DbCompanyId");

                    b.HasIndex("OfferFileId");

                    b.HasIndex("PassportFileId");

                    b.HasIndex("PlanFileId");

                    b.HasIndex("RequestId");

                    b.ToTable("OffersTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullCompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("INN")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("JurAdress")
                        .HasColumnType("text");

                    b.Property<string>("KPP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("LogoFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortCompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyTypeId");

                    b.HasIndex("LogoFileId");

                    b.ToTable("CompaniesTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompanyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TypeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CompanyTypesTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbEquipRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("RequestId");

                    b.ToTable("EquipRequestTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfigTypeId");

                    b.ToTable("EquipmentTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbFavoriteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoritesTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("InnerId")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("NameByProjectDocs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("ProjectOrganizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfigTypeId");

                    b.HasIndex("FileId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectRequestsTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RegionName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RegionsTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbRequestConfigType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigTypeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationTypesTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbSupplierUserCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplierUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SupplierUserId");

                    b.ToTable("SupplierUsersCompaniesTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("UsersTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UsersRolesTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.KNS.DbKnsConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivePumpsCount")
                        .HasColumnType("integer");

                    b.Property<int>("EnvironmentTemperature")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedDiameterOfPumpStation")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedHeightOfPumpStation")
                        .HasColumnType("integer");

                    b.Property<bool>("ExplosionProtection")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasManyExitPressurePipelines")
                        .HasColumnType("boolean");

                    b.Property<int>("InsulatedHousingDepth")
                        .HasColumnType("integer");

                    b.Property<int>("PType")
                        .HasColumnType("integer");

                    b.Property<double>("Perfomance")
                        .HasColumnType("double precision");

                    b.Property<int>("Place")
                        .HasColumnType("integer");

                    b.Property<int>("PowerContactsToController")
                        .HasColumnType("integer");

                    b.Property<int>("PressurePipelineDepth")
                        .HasColumnType("integer");

                    b.Property<int>("PressurePipelineDiameter")
                        .HasColumnType("integer");

                    b.Property<int>("PressurePipelineDirectionInHours")
                        .HasColumnType("integer");

                    b.Property<int>("PressurePipelineMaterial")
                        .HasColumnType("integer");

                    b.Property<int>("PumpsToWarehouseCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<double>("RequiredPumpPressure")
                        .HasColumnType("double precision");

                    b.Property<int>("ReservePumpsCount")
                        .HasColumnType("integer");

                    b.Property<int>("SupplyPipelineDepth")
                        .HasColumnType("integer");

                    b.Property<int>("SupplyPipelineDiameter")
                        .HasColumnType("integer");

                    b.Property<int>("SupplyPipelineDirectionInHours")
                        .HasColumnType("integer");

                    b.Property<int>("SupplyPipelineMaterial")
                        .HasColumnType("integer");

                    b.Property<int>("Units")
                        .HasColumnType("integer");

                    b.Property<int>("startupMethod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("KnsConfigurations", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.PUMP.DbDryPump", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("InstalationType")
                        .HasColumnType("integer");

                    b.Property<Guid>("PumpTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<double>("SuctionHeight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PumpTypeId");

                    b.HasIndex("RequestId");

                    b.ToTable("DryPumps", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.PUMP.DbPumpConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BigParticleExistance")
                        .HasColumnType("boolean");

                    b.Property<string>("ControlType")
                        .HasColumnType("text");

                    b.Property<bool>("ExplosionProtection")
                        .HasColumnType("boolean");

                    b.Property<bool>("FlushValve")
                        .HasColumnType("boolean");

                    b.Property<bool>("FrequencyConverter")
                        .HasColumnType("boolean");

                    b.Property<string>("GeodesicalMarks")
                        .HasColumnType("text");

                    b.Property<int>("IntakeType")
                        .HasColumnType("integer");

                    b.Property<bool>("LiftingTransportEquipment")
                        .HasColumnType("boolean");

                    b.Property<double>("LiquidDensity")
                        .HasColumnType("double precision");

                    b.Property<double>("LiquidTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("MineralParticlesConcentration")
                        .HasColumnType("double precision");

                    b.Property<double>("MineralParticlesSize")
                        .HasColumnType("double precision");

                    b.Property<double>("NetworkLength")
                        .HasColumnType("double precision");

                    b.Property<bool>("OtherLevelMeters")
                        .HasColumnType("boolean");

                    b.Property<string>("OtherRequirements")
                        .HasColumnType("text");

                    b.Property<int>("PipesConditions")
                        .HasColumnType("integer");

                    b.Property<double>("PowerCableLength")
                        .HasColumnType("double precision");

                    b.Property<string>("PowerCurrentType")
                        .HasColumnType("text");

                    b.Property<double>("PressureLoses")
                        .HasColumnType("double precision");

                    b.Property<double>("PumpDiameter")
                        .HasColumnType("double precision");

                    b.Property<double>("PumpEfficiency")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PumpTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("PumpedLiquidType")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<double>("RequiredOutPressure")
                        .HasColumnType("double precision");

                    b.Property<double>("RequiredPressure")
                        .HasColumnType("double precision");

                    b.Property<int>("ReservePumpsCount")
                        .HasColumnType("integer");

                    b.Property<string>("SpecificWastes")
                        .HasColumnType("text");

                    b.Property<double>("WorkPower")
                        .HasColumnType("double precision");

                    b.Property<int>("WorkPumpsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PumpTypeId");

                    b.HasIndex("RequestId");

                    b.ToTable("DbPumpConfiguration", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.PUMP.DbPumpType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TypeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PumpTypes", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.PUMP.DbSubmersiblePump", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("InstalationType")
                        .HasColumnType("integer");

                    b.Property<double>("PotentialDepth")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PumpTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PumpTypeId");

                    b.HasIndex("RequestId");

                    b.ToTable("SubmersiblePumps", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbBusinessOfferFileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("OfferFilesTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbEquipmentCertificateFileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CertificatesFilesTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbEquipmentPassportFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PassportsFilesTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbImageFileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ImageFilesTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbPlanFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PlanFilesTable", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbRequestFileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RequestFiles", (string)null);
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbAccountRequest", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbBusinessAccount", "account")
                        .WithMany("AccountRequests")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", "Request")
                        .WithMany("AccountRequests")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("account");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbBusinessAccount", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", "User")
                        .WithMany("BusinessAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbBusinessOffer", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbBusinessAccount", "BussinessAccount")
                        .WithMany()
                        .HasForeignKey("BussinessAccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.FileStorages.DbEquipmentCertificateFileModel", "CertificateFile")
                        .WithMany("BusinesOffers")
                        .HasForeignKey("CertificateFileId");

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompany", null)
                        .WithMany("CompanyOffers")
                        .HasForeignKey("DbCompanyId");

                    b.HasOne("MarketAnalysisWebApi.DbEntities.FileStorages.DbBusinessOfferFileModel", "BusinesOfferFile")
                        .WithMany("BusinesOffers")
                        .HasForeignKey("OfferFileId");

                    b.HasOne("MarketAnalysisWebApi.DbEntities.FileStorages.DbEquipmentPassportFile", "PassportFile")
                        .WithMany("BusinesOffers")
                        .HasForeignKey("PassportFileId");

                    b.HasOne("MarketAnalysisWebApi.DbEntities.FileStorages.DbPlanFile", "PlanFile")
                        .WithMany("BusinesOffers")
                        .HasForeignKey("PlanFileId");

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", "Request")
                        .WithMany("Offers")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinesOfferFile");

                    b.Navigation("BussinessAccount");

                    b.Navigation("CertificateFile");

                    b.Navigation("PassportFile");

                    b.Navigation("PlanFile");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompany", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompanyType", "CompanyType")
                        .WithMany("Companies")
                        .HasForeignKey("CompanyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.FileStorages.DbImageFileModel", "LogoImage")
                        .WithMany("Companies")
                        .HasForeignKey("LogoFileId");

                    b.Navigation("CompanyType");

                    b.Navigation("LogoImage");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbEquipRequest", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbEquipment", "Equipment")
                        .WithMany("EquipRequests")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", "ProjectRequest")
                        .WithMany("EquipRequest")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("ProjectRequest");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbEquipment", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbRequestConfigType", "Type")
                        .WithMany("Equipments")
                        .HasForeignKey("ConfigTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbFavoriteRequest", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", "request")
                        .WithMany("FavoriteRequests")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", "User")
                        .WithMany("FavoriteRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("request");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbRequestConfigType", "RequestConfigType")
                        .WithMany("ProjectRequests")
                        .HasForeignKey("ConfigTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.FileStorages.DbRequestFileModel", "File")
                        .WithMany("Requests")
                        .HasForeignKey("FileId");

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbRegion", "Region")
                        .WithMany("PRequests")
                        .HasForeignKey("RegionId");

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", "User")
                        .WithMany("UsersRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Region");

                    b.Navigation("RequestConfigType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbRefreshToken", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbSupplierUserCompany", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompany", "SupplierCompany")
                        .WithMany("CompanyUsersLinks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", "SupplierUser")
                        .WithMany("CompanyUsersLinks")
                        .HasForeignKey("SupplierUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplierCompany");

                    b.Navigation("SupplierUser");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbUserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.KNS.DbKnsConfiguration", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", "Request")
                        .WithMany("KnsConfigs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.PUMP.DbDryPump", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.PUMP.DbPumpType", "Type")
                        .WithMany("DryPumps")
                        .HasForeignKey("PumpTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", "Request")
                        .WithMany("DryPumps")
                        .HasForeignKey("RequestId");

                    b.Navigation("Request");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.PUMP.DbPumpConfiguration", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.PUMP.DbPumpType", "Type")
                        .WithMany("PumpCongigs")
                        .HasForeignKey("PumpTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", "Requests")
                        .WithMany("PumpConfigurations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requests");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.PUMP.DbSubmersiblePump", b =>
                {
                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.PUMP.DbPumpType", "Type")
                        .WithMany("SubmersiblePumps")
                        .HasForeignKey("PumpTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", "Request")
                        .WithMany("SubmersiblePumps")
                        .HasForeignKey("RequestId");

                    b.Navigation("Request");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbBusinessAccount", b =>
                {
                    b.Navigation("AccountRequests");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompany", b =>
                {
                    b.Navigation("CompanyOffers");

                    b.Navigation("CompanyUsersLinks");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbCompanyType", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbEquipment", b =>
                {
                    b.Navigation("EquipRequests");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbProjectRequest", b =>
                {
                    b.Navigation("AccountRequests");

                    b.Navigation("DryPumps");

                    b.Navigation("EquipRequest");

                    b.Navigation("FavoriteRequests");

                    b.Navigation("KnsConfigs");

                    b.Navigation("Offers");

                    b.Navigation("PumpConfigurations");

                    b.Navigation("SubmersiblePumps");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbRegion", b =>
                {
                    b.Navigation("PRequests");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbRequestConfigType", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("ProjectRequests");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbUser", b =>
                {
                    b.Navigation("BusinessAccounts");

                    b.Navigation("CompanyUsersLinks");

                    b.Navigation("FavoriteRequests");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UsersRequests");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbEntities.DbUserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.DbRequestConfigurations.PUMP.DbPumpType", b =>
                {
                    b.Navigation("DryPumps");

                    b.Navigation("PumpCongigs");

                    b.Navigation("SubmersiblePumps");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbBusinessOfferFileModel", b =>
                {
                    b.Navigation("BusinesOffers");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbEquipmentCertificateFileModel", b =>
                {
                    b.Navigation("BusinesOffers");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbEquipmentPassportFile", b =>
                {
                    b.Navigation("BusinesOffers");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbImageFileModel", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbPlanFile", b =>
                {
                    b.Navigation("BusinesOffers");
                });

            modelBuilder.Entity("MarketAnalysisWebApi.DbEntities.FileStorages.DbRequestFileModel", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
